tasks:
  - name: Database
    before: |
      # make sure to stop and remove mysql container before starting it again
      docker stop iris-db || true
      docker rm iris-db || true
      docker run --name iris-db -p 127.0.0.1:3306:3306/tcp -e MYSQL_ROOT_PASSWORD=root -d mysql:5.5
  - init: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install -e '.[dev,kazoo]'
      # TODO: wait for mysql
      echo "create database iris;" | mysql -h 127.0.0.1 -u root -proot
      cat db/schema_0.sql | mysql -h 127.0.0.1 -u root -proot iris
      cat db/dummy_data.sql | mysql -h 127.0.0.1 -u root -proot iris
      gp sync-done installation
    command: IRIS_CFG_DB_PASSWORD=root make
  - name: Iris Sender
    init: |
      gp sync-await installation
      source venv/bin/activate
    command: IRIS_CFG_DB_PASSWORD=root make sender

ports:
  # Iris Sender
  - port: 2321
    onOpen: ignore
    visibility: private
  # Iris API
  - port: 16649
    onOpen: open-browser
    visibility: private
  # MySQL
  - port: 3306
    onOpen: ignore
    visibility: private

image:
  file: .gitpod.Dockerfile

